owner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import Display, AddFormClass, DeleteItemClass, EditFormClass, DeleteView


urlpatterns = [
    path('', Display.homeDisplay, name="owner-home"),
    path('add-item', AddFormClass.get_name, name="add-item"),
    path('delete-item/<int:pk>/', DeleteView.as_view(), name='delete-item'),
    path('<int:item_id>/edit-item', EditFormClass.editHandler, name="edit-item"),
]

'''
# path('<int:pk>/delete-item', DeleteItemClass.deleteHandler, name="delete-item"),

'''

shopApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('owner/', include(("owner.urls", 'owner'), namespace='owner')),
    path('auth/', include(("welcome.urls", 'welcome'), namespace='auth')),
    path('', include('welcome.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

welcome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.authPage, name='authHome'),
    path('login', views.loginForm, name='login'),
    path('signup', views.signup, name='signup')
]

owner/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    timeStamp = models.DateTimeField(verbose_name="Time when added") # add auto_now_add=True for auto set in database
    name= models.CharField(max_length=200)
    price=models.IntegerField(verbose_name="Current base MRP")
    visibleToCostumer= models.BooleanField(verbose_name="should costumer see or not")
    profitPercentage=models.FloatField("Profit ratio")
    item_image=models.ImageField(upload_to="images/", null=True, blank=True) #for only becoz its saying field is required after form submit

    def __str__(self):
        return self.name 
    
    '''
    random permission here,
    it will show in admin user page,
    add to allowed user section to allow this permission for that perticular user
    if view setting will match then it will open the link or forbidden will display
    '''
    class Meta:
        permissions = (('can_read_on_sunday', 'Can read only on sunday of the month'), ("can_manage_privilege", "Can manage privileges"), ('can_read_privilege_detail', 'Can read privilege detail'), )
    

welcome/models.py
from django.db import models

# Create your models here.

owner/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.views import View
from django.db import models
from django.forms import ModelForm
from django.urls import reverse, reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# from django.contrib.auth.decorators import login_required, permission_required
# from django.utils.decorators import method_decorator
from django.views.generic.edit import DeleteView

from .models import Item

# Create your views here.

class Display(View):
    def homeDisplay(request):
        context= {
            'page_name': "Home page",
            "items": Item.objects.all(),
            "logged_in_username": request.user.username 
        }
        print(request.user.has_perm)
        return render(request, 'owner/index.html', context)


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'price', 'visibleToCostumer', 'profitPercentage', 'timeStamp', 'item_image']

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['item_image'].required = False


class AddFormClass:
    def get_name(request):
        # if this is a POST request we need to process the form data
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = ItemForm(request.POST, request.FILES)    #request.FILES is needed to store the file in static folder and in database also
            # check whether it's valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required
                print("Item details = ", form.cleaned_data)
                form.save()
                # redirect to a new URL:
                # return HttpResponse('/thanks/')   $todo: add latter a success message on screen
                return HttpResponseRedirect('/owner')


        # if a GET (or any other method) we'll create a blank form
        else:
            form = ItemForm()

        return render(request, 'owner/addItem.html', {'form': form})

class DeleteItemClass:
    def deleteHandler(request, pk): # this pk is the argument from index.htm & urls.py
        toBeDeletedItem = Item.objects.get(pk=pk)
        toBeDeletedItem.delete()
        return HttpResponseRedirect(reverse('owner:owner-home'))

# automatically loads item_confirm_delete.html as it is a edfault template style
# @permission_required('owner.can_delete_item')
# @method_decorator(permission_required, name='owner.can_delete_item')
class DeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Item
    permission_required = 'owner.can_delete_item'
    context_object_name = 'item'
    success_url = reverse_lazy('owner:owner-home')


class EditFormClass:
    def editHandler(request, item_id):
        toBeEditedItem = Item.objects.get(pk=item_id)
        itemImagePath = toBeEditedItem.item_image   #only added to show image in UI

        if request.method == 'POST':
            form = ItemForm(request.POST, request.FILES, instance=toBeEditedItem)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/owner')
        else:
            form = ItemForm(instance=toBeEditedItem)

        return render(request, 'owner/editItem.html', {'form': form, 'itemImagePath':itemImagePath})

welcome/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import auth, messages
from django.contrib.auth.models import User

# Create your views here.


def loginForm (request):
    print('login process started')
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        print(email)
        print(password)

        if email == "" or password == "":
            messages.error(request,'Fill the valid data in credentials')
            return redirect('/auth') 
        if User.objects.filter(email=email).exists():
            userName = User.objects.filter(email=email).values_list('username', flat=True).get()
            user = auth.authenticate(request, username=userName, password=password)
            if user is not None:
                auth.login(request, user)
                messages.success(request, 'Login realizado com sucesso, Bem Vindo {} !'.format(user))
                print('user is good')
                return redirect ('/owner')
            else:
                print('user is NOT good')

    return redirect('/auth')


def authPage (request):
    return render(request, 'welcome/login.html')

def signup(request):
    print('now new user will sign up')
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        print(email)
        print(password)

        if email == "" or password == "":
            messages.error(request,'Fill the valid data in credentials')
            return redirect('/auth') 
        else:
            return redirect ('/owner')

    return redirect('/auth')

owner/templates/owner/addItem.html
{% extends 'owner/main.html' %}
{% load static %}
{% block content %}


    <div class="form-style">
        <form action="add-item" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit"> </button>
        </form>
    </div>

    <button> <a href="{% url 'owner:owner-home'%}"> BACK to Home </a> </button>

{% endblock content %}

owner/templates/owner/editItem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item details page</title>
    <style>
        label {
            color:blue;
            display: block;
        }
        img{
            width: 200px;
            max-height: 20%;
        }
        input {
            display: inline;
            position: relative;
            width: 100%;
        }
        input, select {
            border: 1px solid rgb(248, 19, 172);
            border-radius: 4px;
            box-sizing: border-box;
        }

        p,label,input {
            padding: 5px;
            margin: 2px 0 0 10%;
        }
        
        input[type=submit] {
            width: 50%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0 0 30px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .form-style{
            width: 100%;
            background-color: rgb(250, 198, 198);
            display: flex;
            justify-content: left;
        }

    </style>
</head>
<body>
    {% load static%}
    <img src="{% static itemImagePath %}" alt="My image" class="product-image">

    <div class="form-style">
        <form action="edit-item" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit"> </button>
        </form>
    </div>
    
    <button> <a href="{% url 'owner:owner-home'%}"> BACK to Home </a> </button>

</body>
</html>

owner/templates/owner/index.html
{% extends 'owner/main.html' %}
{% block content %}
{% load static %}

    <div class="container">
        <div class="row">
            {% if items %}
            {% for item in items %}
            <ul class="item-style">
                {% if item.visibleToCostumer %}

                <div class="card" style="width: 18rem;">
                    <img src="{% static item.item_image %}" class="card-img-top" alt="product image">
                    <div class="card-body">
                        <h5 class="card-title"> {{item.name}} </h5>
                        <p class="card-text"> ID: {{item.id}} </p>
                        <p class="card-text"> PRICE: {{item.price}} </p>
                        <p class="card-text"> TIMESTAMP: {{item.timeStamp}} </p>
                        <div class="right-portion item-style">
                            <button class="btn" style="background-color: yellow;"> <a
                                    href="{% url 'owner:edit-item' item_id=item.id %}"> EDIT </a> </button>
                            {#% if logged_in_username == 'nilipta' %#}
                            <button class="btn" style="background-color: crimson;"> <a
                                    href="{% url 'owner:delete-item' pk=item.id %}"> DELETE </a></button>
                            {#% endif %#}
                        </div>
                    </div>
                </div>
                {% endif %}
            </ul>
            {% endfor %}
            {% else %}
            <h1>No items in shop</h1>
            {% endif %}
        </div>
    </div>

    {% endblock content %}

owner/templates/owner/item_confirm_delete.html
{% extends 'owner/main.html' %}
{% load static %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'owner:owner-home' %}">&#8592;Go Back</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this task? "{{item}}"</p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>

{% endblock content %}

owner/templates/owner/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{page_name}} </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Navbar</a>
            <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'owner:owner-home'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'owner:add-item'%}"> Add new </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    <a href="/auth"><img src="{% static 'images/login.png' %}" alt="login image" class="img-thumbnail" style="height: 37px; max-width: 40px;"> </a>
                    <label style="padding: 2px 2px; border: 2px solid black;">{{logged_in_username}}</label>
                </form>
            </div>
        </div>
    </nav>


    {% block content %} {% endblock content %}



    
</body>

</html>̥̥̥

welcome/templates/welcome/login.html
{% extends 'owner/main.html' %}
{% load static %}
{% block content %}

    <p class="description description-second">Signup using email & password</p>
    <form action="{%  url 'welcome:signup'  %}"  method="POST">
        {% csrf_token %}
        <label class="label.input" for="">
            <i class="fas fa-user icon-modify"></i>
            <input type="text" name="name"  placeholder="Name" required>
        </label>

        <label class="label.input" for="">
            <i class="fas fa-envelope icon-modify"></i>
            <input type="email" name="email" placeholder="Email" required>
        </label>

        <label class="label.input" for="">
            <i class="fas fa-lock icon-modify"></i>
            <input type="password" name="password" placeholder="password" id="password" required>
        </label>     

        <label class="label.input" for="">
            <i class="fas fa-lock icon-modify"></i>
            <input type="password" name="password2" placeholder="Confirmar password" id="confirm_password" required>
        </label>     
        <button class="btn btn-second">sign up</button>
    </form>



    <p class="description description-second">or use your email account</p>
    <form class="formulario" action="{% url 'welcome:login'  %}" method="POST">
        {% csrf_token %}
        <label class="label.input" for="">
            <i class="fas fa-envelope icon-modify"></i>
            <input type="email" name="email" placeholder="Email">
        </label>
        <label class="label.input" for="">
            <i class="fas fa-lock icon-modify"></i>
            <input type="password" name="password" placeholder="Senha">
        </label>
        <button class="btn btn-primary">Sign in</button>
    </form>

    {% endblock content %}